version: 2.1
commands:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID
jobs:
  mytestjob:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
      - run: return 1
      - run:
        name: what an error
        command: echo "complete failure"
        when: on_fail


workflows:
  my workflow:
    jobs:
      - mytestjob

â€š